// Importación centralizada de Ionicons
import { addIcons } from 'ionicons';
import {
  cloudDoneOutline,
  cloudOfflineOutline,
  cloudOutline,
  cloudUploadOutline,
  refresh,
  refreshOutline,
  storefrontOutline,
  addOutline,
  add,
  trashOutline,
  createOutline,
  searchOutline,
  search,
  cartOutline,
  personOutline,
  chatbubbleOutline,
  homeOutline,
  logOutOutline,
  cameraOutline,
  camera,
  imageOutline,
  imagesOutline,
  closeOutline,
  closeCircle,
  checkmarkOutline,
  checkmarkCircle,
  alertCircleOutline,
  informationCircleOutline,
  arrowBack,
  chevronBack,
  chevronForward,
  settings,
  filter,
  cube,
  timeOutline,
  peopleOutline,
  eyeOutline,
  star
} from 'ionicons/icons';

// Registrar todos los iconos usados en la aplicación
export function registerIcons() {
  addIcons({
    'cloud-done-outline': cloudDoneOutline,
    'cloud-offline-outline': cloudOfflineOutline,
    'cloud-outline': cloudOutline,
    'cloud-upload-outline': cloudUploadOutline,
    'refresh': refresh,
    'refresh-outline': refreshOutline,
    'storefront-outline': storefrontOutline,
    'add-outline': addOutline,
    'add': add,
    'trash-outline': trashOutline,
    'create-outline': createOutline,
    'search-outline': searchOutline,
    'search': search,
    'cart-outline': cartOutline,
    'person-outline': personOutline,
    'chatbubble-outline': chatbubbleOutline,
    'home-outline': homeOutline,
    'log-out-outline': logOutOutline,
    'camera-outline': cameraOutline,
    'camera': camera,
    'image-outline': imageOutline,
    'images-outline': imagesOutline,
    'close-outline': closeOutline,
    'close-circle': closeCircle,
    'checkmark-outline': checkmarkOutline,
    'checkmark-circle': checkmarkCircle,
    'alert-circle-outline': alertCircleOutline,
    'information-circle-outline': informationCircleOutline,
    'arrow-back': arrowBack,
    'chevron-back': chevronBack,
    'chevron-forward': chevronForward,
    'settings': settings,
    'filter': filter,
    'cube': cube,
    'time-outline': timeOutline,
    'people-outline': peopleOutline,
    'eye-outline': eyeOutline,
    'star': star
  });
}
